name: Insta Bot Worker
on:
  workflow_dispatch:
    inputs:
      target_url:
        required: true
      chat_id:
        required: true
      cookie_1:
        required: true
      cookie_2:
        required: false

jobs:
  run-bot:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.run_id }} 
    steps:
      - uses: actions/checkout@v3

      # 👇 1. YAHAN VPN LAGA RAHE HAIN (Sabse pehle IP change hogi) 👇
      - name: Setup Cloudflare WARP VPN (Free IP Changer)
        uses: ryandoyle/setup-cloudflare-warp@v1.2.0
      
      # 🔍 2. Check IP (Log me dikhega ki IP sach me change hui ya nahi)
      - name: Check new IP Address
        run: curl -s https://ipinfo.io/json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install playwright requests python-dotenv
          playwright install chromium
          
      - name: Run Bot Worker
        env:
          TARGET_URL: ${{ github.event.inputs.target_url }}
          CHAT_ID: ${{ github.event.inputs.chat_id }}
          COOKIE_1: ${{ github.event.inputs.cookie_1 }}
          COOKIE_2: ${{ github.event.inputs.cookie_2 }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        run: python worker.py
